name: Deploy VuePress Site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 安装node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.16.0

      - name: 安装依赖
        run: yarn

      - name: 打包
        run: yarn docs:build

      - name: Deploy to GitHub Pages Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./build
          external_repository: lzwcyd/lzwcyd.github.io
          keep_files: true
          user_name: 'GitHub Actions'
          user_email: 'actions@github.com'
          commit_message: 'Deploy VuePress site'